name: to_sqlite
description: to_sqlite is a CLI tool which helps to convert CSV files into SQLite databases and model classes.

version: 0.1.4
repository: https://github.com/sidha6th/to_sqlite

environment:
  sdk: ^3.4.3

executables:
  toSqlite: to_sqlite

dependencies:
  args: ^2.5.0
  collection: ^1.18.0
  path: ^1.9.0
  sqlite3: ^2.4.6

dev_dependencies:
  dart_flutter_team_lints: ^2.1.1
  lints: ^3.0.0
  test: ^1.24.0
